<a href="https://colab.research.google.com/github/Ryukijano/T-T-lab-6th-sem/blob/main/t%26t_final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###NAME- GYANATEET DUTTA
###ROLL No - 1930198
###SECTION- ECS2
###T&T LAB 8

In [1]:
#1. Write a program to create a 2D array with 1 on the border and a inside.
import numpy as np
a=np.ones((5,5))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [2]:
#2. Write a program to create a 4X4 matrix with values 1,2,3,4 just below & above the diagonal, rest 0
import numpy as np
b=np.zeros((4,4))
b=np.diag(np.arange(1,5))
print(b)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [3]:
#3. Write a program to extract all the contiguous 3X3 blocks from a random 10X10 matrix
import numpy as np
c=np.random.randint(1,10,(10,10))
print("The random 10X10 matrix is:")
print (c)
d=np.zeros((10,10))
d=c[0:3,0:3]
print("The first 3X3 block is:")
print (d)
d=c[0:3,3:6]
print("The second 3X3 block is:")
print(d)
d=c[0:3,6:10]
print("The third 3X3 block is:")
print(d)
d=c[3:6,0:3]
print("The fourth 3X3 block is:")
print(d)
d=c[3:6,3:6]
print("The fifth 3X3 block is:")
print(d)
d=c[3:6,6:10]
print("The sixth 3X3 block is:")
print(d)
d=c[6:10,0:3]
print("The seventh 3X3 block is:")
print(d)
d=c[6:10,3:6]
print("The eighth 3X3 block is:")
print(d)
d=c[6:10,6:10]
print("The ninth 3X3 block is:")
print(d)

The random 10X10 matrix is:
[[8 1 7 7 2 8 4 5 2 7]
 [3 2 6 1 8 6 5 1 1 3]
 [9 8 2 7 5 1 4 8 5 9]
 [1 5 2 2 7 6 4 4 5 4]
 [3 3 7 6 6 8 5 7 8 2]
 [4 3 4 3 1 9 1 9 4 9]
 [1 1 6 2 9 1 7 9 4 4]
 [5 9 2 3 8 8 7 7 6 4]
 [4 2 9 9 8 1 7 5 3 9]
 [4 7 4 3 5 6 9 6 2 4]]
The first 3X3 block is:
[[8 1 7]
 [3 2 6]
 [9 8 2]]
The second 3X3 block is:
[[7 2 8]
 [1 8 6]
 [7 5 1]]
The third 3X3 block is:
[[4 5 2 7]
 [5 1 1 3]
 [4 8 5 9]]
The fourth 3X3 block is:
[[1 5 2]
 [3 3 7]
 [4 3 4]]
The fifth 3X3 block is:
[[2 7 6]
 [6 6 8]
 [3 1 9]]
The sixth 3X3 block is:
[[4 4 5 4]
 [5 7 8 2]
 [1 9 4 9]]
The seventh 3X3 block is:
[[1 1 6]
 [5 9 2]
 [4 2 9]
 [4 7 4]]
The eighth 3X3 block is:
[[2 9 1]
 [3 8 8]
 [9 8 1]
 [3 5 6]]
The ninth 3X3 block is:
[[7 9 4 4]
 [7 7 6 4]
 [7 5 3 9]
 [9 6 2 4]]


In [4]:
#4. A magic square is a matrix all of whose row sums, column sums, and  the sums of the two diagonals are the same.(One diagonal of a matrix goes from the top left to the bottom right, and the other diagonal goes from the top right to the bottom left.) Show by direct computation that if the matrix A is given by
#A=np.array([[17,24,1,8,15],[23,5,7,14,16],[4,6,13,20,22],[10,12,19,21,3],[11,18,25,2,9]])
#The matrix A has 5-rows sums (one for each row) , 5-column sums (one for each column), and two diagonal sums. These 12 sums should all be exactly the same, and you could verify that they are the same by printing them and "seeing" that they are all the same.It is easy to miss small differences among so many numbers,though. Instead, verify that A is a magic square by constructing the 5 column sums and computing the maximum and minimum values of the column sums. Do the same for 5-row sums, and compute the two diagonal sums. Check that these six values are the same. If the maximum and minimum values are the same, the flyswatter principle says that all values are the same. If the maximum and minimum values are different, the flyswatter principle says that the matrix is not a magic square.
import numpy as np
A=np.array([[17,24,1,8,15],[23,5,7,14,16],[4,6,13,20,22],[10,12,19,21,3],[11,18,25,2,9]])
print("The sum of the rows of A is:")
print(A.sum(axis=1))
print("The sum of the columns of A is:")
print(A.sum(axis=0))
print("The sum of the two diagonals of A is:")
print(A.diagonal())
print("The maximum value of the column sums of A is:")
print(A.sum(axis=0).max())
print("The minimum value of the column sums of A is:")
print(A.sum(axis=0).min())
print("The maximum value of the row sums of A is:")
print(A.sum(axis=1).max())
print("The minimum value of the row sums of A is:")
print(A.sum(axis=1).min())
if A.sum(axis=0).max()==A.sum(axis=0).min():
    print("The flyswatter principle says that all values are the same.")
else:
    print("The flyswatter principle says that the matrix is not a magic square.")


The sum of the rows of A is:
[65 65 65 65 65]
The sum of the columns of A is:
[65 65 65 65 65]
The sum of the two diagonals of A is:
[17  5 13 21  9]
The maximum value of the column sums of A is:
65
The minimum value of the column sums of A is:
65
The maximum value of the row sums of A is:
65
The minimum value of the row sums of A is:
65
The flyswatter principle says that all values are the same.
